// Writes desktop/shell.nsh: the Windows "Open with Mobius 3D" verbs, generated
// from brand.json and formats.json so the two can never disagree. It ADDS A
// VERB and nothing else -- per user, under SystemFileAssociations -- and never
// touches an extension's default program or the UserChoice keys.
const fs = require('node:fs');
const brand = require('./brand.json');
const { extensions } = require('./formats.json');
if (!/^[A-Za-z][A-Za-z0-9 .-]*$/.test(brand.name) || !/^[A-Za-z0-9.]+$/.test(brand.shellVerb) || !/^[A-Za-z0-9]+$/.test(brand.executable)) {
  throw Error('Invalid Windows brand configuration');
}
const exe = `$INSTDIR\\${brand.executable}.exe`;
const key = ext => `Software\\Classes\\SystemFileAssociations\\.${ext}\\shell\\${brand.shellVerb}`;
const install = extensions.map(ext => `  WriteRegStr HKCU "${key(ext)}" "" "Open with ${brand.name}"
  WriteRegStr HKCU "${key(ext)}" "Icon" '"${exe}",0'
  WriteRegStr HKCU "${key(ext)}\\command" "" '"${exe}" "%1"'`).join('\n');
/* AND IN THE "Open with" LIST. The verb above is a line of its own on the
   classic menu, which Windows 11 hides under "Show more options". Listing a
   ProgID under each extension's OpenWithProgids is what puts Mobius 3D in the
   modern menu's Open with submenu -- still never the default: OpenWithProgids
   only OFFERS a program, it does not choose one. */
const progId = `${brand.executable}.Model`;
const install2 = [
  `  WriteRegStr HKCU "Software\\Classes\\${progId}" "" "3D model"`,
  `  WriteRegStr HKCU "Software\\Classes\\${progId}\\DefaultIcon" "" '"${exe}",0'`,
  `  WriteRegStr HKCU "Software\\Classes\\${progId}\\shell\\open" "FriendlyAppName" "${brand.name}"`,
  `  WriteRegStr HKCU "Software\\Classes\\${progId}\\shell\\open\\command" "" '"${exe}" "%1"'`,
  ...extensions.map(ext => `  WriteRegStr HKCU "Software\\Classes\\.${ext}\\OpenWithProgids" "${progId}" ""`),
  `  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'`,
].join('\n');
const uninstall = [...extensions.map(ext => `  DeleteRegKey HKCU "${key(ext)}"
  DeleteRegValue HKCU "Software\\Classes\\.${ext}\\OpenWithProgids" "${progId}"`),
  `  DeleteRegKey HKCU "Software\\Classes\\${progId}"`,
  `  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'`].join('\n');
fs.writeFileSync('desktop/shell.nsh', `; Generated by desktop/prepare.cjs. Adds Open with entries only; never sets extension defaults.
!macro customInstall
${install}
${install2}
!macroend
!macro customUnInstall
${uninstall}
!macroend
`);
console.log(`shell.nsh: ${extensions.length} extensions, ${extensions.length * 4 + 4} registry values`);
