// Writes desktop/shell.nsh: the Windows "Open with Mobius 3D" verbs, generated
// from brand.json and formats.json so the two can never disagree. It ADDS A
// VERB and nothing else -- per user, under SystemFileAssociations -- and never
// touches an extension's default program or the UserChoice keys.
const fs = require('node:fs');
const brand = require('./brand.json');
const { extensions } = require('./formats.json');
if (!/^[A-Za-z][A-Za-z0-9 .-]*$/.test(brand.name) || !/^[A-Za-z0-9.]+$/.test(brand.shellVerb) || !/^[A-Za-z0-9]+$/.test(brand.executable)) {
  throw Error('Invalid Windows brand configuration');
}
const exe = `$INSTDIR\\${brand.executable}.exe`;
const key = ext => `Software\\Classes\\SystemFileAssociations\\.${ext}\\shell\\${brand.shellVerb}`;
const install = extensions.map(ext => `  WriteRegStr HKCU "${key(ext)}" "" "Open with ${brand.name}"
  WriteRegStr HKCU "${key(ext)}" "Icon" '"${exe}",0'
  WriteRegStr HKCU "${key(ext)}\\command" "" '"${exe}" "%1"'`).join('\n');
const uninstall = extensions.map(ext => `  DeleteRegKey HKCU "${key(ext)}"`).join('\n');
fs.writeFileSync('desktop/shell.nsh', `; Generated by desktop/prepare.cjs. Adds a verb only; never sets extension defaults.
!macro customInstall
${install}
!macroend
!macro customUnInstall
${uninstall}
!macroend
`);
console.log(`shell.nsh: ${extensions.length} extensions, ${extensions.length * 3} registry values`);
