; Generated by desktop/prepare.cjs. Adds Open with entries only; never sets extension defaults.
!macro customInstall
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\Mobius3D.Model" "" "3D model"
  WriteRegStr HKCU "Software\Classes\Mobius3D.Model\DefaultIcon" "" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\Mobius3D.Model\shell\open" "FriendlyAppName" "Mobius 3D"
  WriteRegStr HKCU "Software\Classes\Mobius3D.Model\shell\open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\.glb\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.gltf\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.fbx\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.obj\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.ply\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.stl\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.dae\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.3mf\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.3ds\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.usdz\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.usd\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.usda\OpenWithProgids" "Mobius3D.Model" ""
  WriteRegStr HKCU "Software\Classes\.usdc\OpenWithProgids" "Mobius3D.Model" ""
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'
!macroend
!macro customUnInstall
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.glb\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.gltf\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.fbx\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.obj\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.ply\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.stl\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.dae\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.3mf\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.3ds\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.usdz\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.usd\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.usda\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open"
  DeleteRegValue HKCU "Software\Classes\.usdc\OpenWithProgids" "Mobius3D.Model"
  DeleteRegKey HKCU "Software\Classes\Mobius3D.Model"
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'
!macroend
