; Generated by desktop/prepare.cjs. Adds a verb only; never sets extension defaults.
!macro customInstall
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open" "" "Open with Mobius 3D"
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open" "Icon" '"$INSTDIR\Mobius3D.exe",0'
  WriteRegStr HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open\command" "" '"$INSTDIR\Mobius3D.exe" "%1"'
!macroend
!macro customUnInstall
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.glb\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.gltf\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.fbx\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.obj\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.ply\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.stl\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.dae\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.3mf\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.3ds\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usdz\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usd\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usda\shell\Mobius3D.Open"
  DeleteRegKey HKCU "Software\Classes\SystemFileAssociations\.usdc\shell\Mobius3D.Open"
!macroend
